// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_h7n_pfte1OeB-GwnigPQyYcmZ_mtcyA',
    appId: '1:612639536269:web:cc923cdc8c02d6a1b69ec4',
    messagingSenderId: '612639536269',
    projectId: 'diaryapp-d2ec9',
    authDomain: 'diaryapp-d2ec9.firebaseapp.com',
    databaseURL: 'https://diaryapp-d2ec9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diaryapp-d2ec9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKC5ufDzmfEktPJjydFAriL8itDJg2Jjo',
    appId: '1:612639536269:android:53e1c3c40d7bf523b69ec4',
    messagingSenderId: '612639536269',
    projectId: 'diaryapp-d2ec9',
    databaseURL: 'https://diaryapp-d2ec9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diaryapp-d2ec9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnZfYWoxiutbJb7bUGLuIsz3ro_8HNT_U',
    appId: '1:612639536269:ios:70c62eba2dc151b4b69ec4',
    messagingSenderId: '612639536269',
    projectId: 'diaryapp-d2ec9',
    databaseURL: 'https://diaryapp-d2ec9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diaryapp-d2ec9.appspot.com',
    androidClientId: '612639536269-reb0kje4tpill94i7sv6113fkl0ool42.apps.googleusercontent.com',
    iosClientId: '612639536269-i108n7g5gt6epf029l8o260ku7aboo98.apps.googleusercontent.com',
    iosBundleId: 'com.example.module04',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnZfYWoxiutbJb7bUGLuIsz3ro_8HNT_U',
    appId: '1:612639536269:ios:594da636d47b7831b69ec4',
    messagingSenderId: '612639536269',
    projectId: 'diaryapp-d2ec9',
    databaseURL: 'https://diaryapp-d2ec9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diaryapp-d2ec9.appspot.com',
    androidClientId: '612639536269-reb0kje4tpill94i7sv6113fkl0ool42.apps.googleusercontent.com',
    iosClientId: '612639536269-m7741iimmbn1sbupre8o15k8ek4hgj0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.module04.RunnerTests',
  );
}
